### ISSUE TITLE
Cordova PSPFKIT problem displaying the pdf

### ISSUE THREAD

**Issue by mohamadnajiya** [PSPDFKit/Cordova-Android#12]
Hello,
I am trying to use the cordova PSPFKIT in visual studio 2017

I have done the below

1.  Added https://github.com/PSPDFKit/Cordova-Android.git plugin to my project

2. Copied pspdfkit-3.1.1.aar under platforms/android/libs/

3. Set min sdk to 16

4. Added my demo license key to AndroidManifest.xml

5. Added a pdf file "myFile.pdf" under "www/documents"

6. Added the below  under onDeviceReady method in index.js

```
 PSPDFKit.showDocumentFromAssets('www/documents/myFile.pdf', {
            title: 'My PDF Document',
           
            scrollDirection: PSPDFKit.PageScrollDirection.VERTICAL,
            scrollMode: PSPDFKit.ScrollMode.CONTINUOUS,
            useImmersiveMode: true
        });
```
The application is loaded with no errors but the pdf file is not displayed.

Thx,

**Comment by davidschreiber** [comment]
Hi @mohamadnajiya,

There's not much I can comment on here. Your calling code looks fine. I assume that your Cordova application is throwing some error which prevents successful execution of the code. By default, Cordova tends to eagerly swallow exceptions. Try registering a global Javascript error handler in your HTML to see if any exceptions are thrown (see for example error handling here: https://stackoverflow.com/questions/951791/javascript-global-error-handling)

I'm closing this issue, since it is very likely not directly related with PSPDFKit or the Cordova plugin.
