### ISSUE TITLE
Pdf open password calling automatically when opening 

### ISSUE THREAD

**Issue by raju1979** [PSPDFKit/Cordova-Android#18]
Is there any way to pass the pdf open password while calling PSPDFKit.showDocument.

**Comment by davidschreiber** [comment]
Hi,

Right now, the Cordova wrapper does not support opening of encrypted PDF documents. However, since PSPDFKit APIs already provide this functionality, extending the wrapper should be a fairly trivial task. We're always grateful for contributions and would love to integrate your PR on this.

Here is the PSPDFKit method for opening encrypted PDFs:
https://pspdfkit.com/api/android/reference/com/pspdfkit/ui/PdfActivity.html#showDocument(android.content.Context, android.net.Uri, java.lang.String, com.pspdfkit.configuration.activity.PdfActivityConfiguration)

Here is the line wrapper code part responsible for opening the document. It would be necessary to pass over a password to the wrapper and open the document using it:
https://github.com/PSPDFKit/Cordova-Android/blob/master/src/android/java/com/pspdfkit/cordova/PSPDFKitCordovaPlugin.java#L244

**Comment by raju1979** [comment]
So if I use native android plugin I can pass password to open the pdf from SDCard?

**Comment by davidschreiber** [comment]
Yes. This is possible. To see the full capabilities of PSPDFKit for Android you can also try our PDF Viewer app: https://pdfviewer.io/store-android

**Comment by raju1979** [comment]
I will try to make a PR, once I know how to do it. ;).
Just one more question, does cordova plugin support DRM books pdf.

**Comment by steipete** [comment]
What DRM are you referring to? Passwords?

**Comment by raju1979** [comment]
Is it possible to open Adobe DRM protected pdf in pspdfkit?

**Comment by steipete** [comment]
Adobe DRM is a proprietary technology and only compatible with Adobe products:
https://en.wikipedia.org/wiki/Adobe_Digital_Editions

You can build similar protection with our products using industry standard AES encryption:
https://pspdfkit.com/guides/ios/current/security/introduction-to-encryption/

This will require some work - we offer the building blocks to get everything right.
